# Generated by Django 6.0.2 on 2026-02-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pen_name',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
